export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const USER_REGISTERED= "USER_REGISTERED";
export const LOAD_DASHBOARD_DATA= "LOAD_DASHBOARD_DATA";
export const LOG_OUT ="LOG_OUT";
export const REMOVE_TICKER_FROM_WATCHLIST = "REMOVE_TICKER_FROM_WATCHLIST";
export const ADD_TICKER_TO_WATCHLIST = "ADD_TICKER_TO_WATCHLIST";
export const LOAD_TRADE_DETAIL_DASHBOARD="LOAD_TRADE_DETAIL_DASHBOARD"

export const LOAD_TRADE_DETAIL_MODAL="LOAD_TRADE_DETAIL_MODAL"
export const INCREMENT_STOCK_QUANTITY="INCREMENT_STOCK_QUANTITY"
export const DECREMENT_STOCK_QUANTITY="DECREMENT_STOCK_QUANTITY"
export const INCREMENT_STOCK_STOP_LOSS="INCREMENT_STOCK_STOP_LOSS"
export const DECREMENT_STOCK_STOP_LOSS="DECREMENT_STOCK_STOP_LOSS"
export const INCREMENT_STOCK_PROFIT_TARGET="INCREMENT_STOCK_PROFIT_TARGET"
export const DECREMENT_STOCK_PROFIT_TARGET="DECREMENT_STOCK_PROFIT_TARGET"
export const UPDATE_STOP_LOSS="UPDATE_STOP_LOSS"
export const INCREMENT_STOP_LOSS="INCREMENT_STOP_LOSS"
export const DECREMENT_STOP_LOSS="DECREMENT_STOP_LOSS"
export const UPDATE_PROFIT_TARGET="UPDATE_PROFIT_TARGET"
export const INCREMENT_PROFIT_TARGET="INCREMENT_PROFIT_TARGET"
export const DECREMENT_PROFIT_TARGET="DECREMENT_PROFIT_TARGET"
export const SET_PROFIT_TARGET_VALIDITY="SET_PROFIT_TARGET_VALIDITY"
export const SET_STOP_LOSS_VALIDITY="SET_STOP_LOSS_VALIDITY"
export const UPDATE_TRADE_DETAIL="UPDATE_TRADE_DETAIL"
export const DELETE_TRADE_DETAIL= "DELETE_TRADE_DETAIL"
export const REFRESH_TRADE_MODAL="REFRESH_TRADE_MODAL"
export const LOAD_WATCHLIST = "LOAD_WATCHLIST";
export const GET_OPEN_TARDE_LIST = "GET_OPEN_TARDE_LIST";
export const GET_ClOSE_TARDE_LIST = "GET_ClOSE_TARDE_LIST";
export const GET_WINNING_TRADE_LIST = "GET_WINNING_TRADE_LIST";
export const GET_LOSING_TRADE_LIST = "GET_LOSING_TRADE_LIST";
export const INVALID_ACCESS_TOKEN= "INVALID_ACCESS_TOKEN";
export const LOAD_USER_WATCHLIST= "LOAD_USER_WATCHLIST";
export const AUTH_WITH_TOKEN= "AUTH_WITH_TOKEN";
export const SET_LOADING="SET_LOADING";


