export const dashboardBaseURL = "/api/trade/dashboard";
export const loginURL = "/api/auth/login";
export const signUpURL = "/api/auth/signup";
export const resetPasswordURL = "/api/auth/reset-password";
export const updatedPasswordURL = "/api/auth/user/edit";
export const userDataURL = "/api/auth/user";
export const addToWatchlistUrl = "/api/user/watchlist/add";
export const deleteFromWatchlistUrl = "/api/user//watchlist/delete";
export const getWatchlistUrl = "/api/user/watchlist";

export const tradeAlertDataURL = "/api/trade/trade-alert";
export const tradeMicroServiceUrl = "/api/trade";
export const deleteTradeAlertUrl = "/api/alert";
export const getTradeDetailsUrl = "/api/trade/alert-to-details";
export const searchTickerURL = "/api/user/tickers/search";
export const getTradingDetails = "api/user/get-user-trading-details"
export const postTradingDetails = "api/user/create-update-trading-profile"
export const executeTradeURL = "/trade-detail/execute"
export const deleteTradeURL = "/trade-detail/delete"
export const TRADE_DETAIL_DASHBOARD_URL="/trade-details/fetch"
export const tradeDetailsDashboardURL="/trade-details/fetch"
export const refreshTokenURL = "/api/auth/refreshtoken";
export const getWinningLosingOpenTradesURL = "/api/user/winning-losing-open-trades";
export const getClosedTradesURL = "/api/trade/closed-trades";
export const authWithToken ="/api/auth/validate";
export const getTradeDetailModalURL="/api/trade/trade-detail";
